import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { DailyAttendanceReport } from '../types';

export const generateAttendancePDF = async (report: DailyAttendanceReport) => {
  const doc = new jsPDF();
  
  // Load Company Logo
  const img = new Image();
  img.src = '/logo.png';
  await new Promise((resolve) => {
    img.onload = resolve;
    img.onerror = resolve; // Continue even if logo fails
  });

  // Websums Theme Colors
  const primaryColor = [249, 115, 22]; // Orange 500
  const secondaryColor = [30, 41, 59]; // Slate 800

  // 1. Add Company Logo & Header
  try {
    // Try to add the real image logo (X, Y, Width, Height)
    doc.addImage(img, 'PNG', 14, 12, 18, 18);
  } catch (e) {
    // Fallback geometric logo if image fails
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.roundedRect(14, 15, 12, 12, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('W', 18, 23);
  }

  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('WEBSUMS', 35, 20);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text('Websums Software Pvt. Ltd.', 35, 25);

  // Header separator line
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setLineWidth(0.5);
  doc.line(14, 34, 196, 34);

  // 2. Report Title
  doc.setFontSize(16);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]); // Orange title
  doc.setFont('helvetica', 'bold');
  doc.text('DAILY ATTENDANCE REPORT', 14, 45);

  // 3. Report Metadata (Grid style)
  const dateStr = new Date(report.date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
  
  // Left Side (Batch & Mentor)
  doc.setFontSize(10);
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('Batch:', 14, 54);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(report.batch, 35, 54);

  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('Mentor:', 14, 60);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(report.mentorName, 35, 60);

  // Right Side (Date)
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('Date:', 125, 54);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(dateStr, 137, 54);

  // 4. Statistics Summary Box
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 70, 180, 20, 3, 3, 'FD');
  
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(`Total Interns: ${report.totalStudents}`, 20, 82);
  
  doc.setTextColor(16, 185, 129); // Emerald 500
  doc.text(`Present: ${report.presentCount}`, 70, 82);
  
  doc.setTextColor(244, 63, 94); // Rose 500
  doc.text(`Absent: ${report.absentCount}`, 120, 82);
  
  doc.setTextColor(245, 158, 11); // Amber 500
  doc.text(`Late: ${report.lateCount}`, 165, 82);

  // 5. Attendance Table
  const tableColumn = ["ID", "Student Name", "Domain", "Status"];
  const tableRows: any[] = [];

  report.records.forEach(record => {
    const rowData = [
      record.studentId.replace('std-', ''),
      record.studentName,
      record.domain,
      record.status
    ];
    tableRows.push(rowData);
  });

  autoTable(doc, {
    startY: 95,
    head: [tableColumn],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: secondaryColor,
      textColor: 255,
      fontSize: 10,
      fontStyle: 'bold',
      halign: 'left'
    },
    bodyStyles: {
      fontSize: 9,
      textColor: 50
    },
    columnStyles: {
      3: { fontStyle: 'bold' }
    },
    didParseCell: function(data: any) {
      // Color-code the status column
      if (data.section === 'body' && data.column.index === 3) {
        if (data.cell.raw === 'Present') {
          data.cell.styles.textColor = [16, 185, 129]; // Emerald
        } else if (data.cell.raw === 'Absent') {
          data.cell.styles.textColor = [244, 63, 94]; // Rose
        } else if (data.cell.raw === 'Late') {
          data.cell.styles.textColor = [245, 158, 11]; // Amber
        }
      }
    }
  });

  // 6. Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by Websums Management System • Page ${i} of ${pageCount}`, 14, doc.internal.pageSize.getHeight() - 10);
  }

  // Save the PDF
  doc.save(`Websums_Attendance_${report.batch}_${report.date}.pdf`);
};
